[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Clear-Site-Data = "\"storage\""

[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/git-gateway/*"
  to = "/.netlify/git-gateway/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
